version: '3.8'
services:
  dev:
    image: gupta840/appname
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.4dxvdyw.mongodb.net
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - KAFKA_ID=appname
      - DATABASE=appname
      - KAFKA_1=kafka:9092
      - JWT_KEY=something
      - ENV=development # Overrides the container level env vaiables
      - PORT=8080

  live:
    image: gupta840/appname
    restart: always
    ports:
      - "8080:8081"
    environment:
      - MONGO_URI=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.4dxvdyw.mongodb.net
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - KAFKA_ID=appname
      - DATABASE=appname
      - KAFKA_1=kafka:9092
      - JWT_KEY=something
      - ENV=production # No need to do this because image has by default "production" value in ENV
      - PORT=8080
