version: '3.9'
services:
  appname-frontend:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - /app/build
      - ./client:/app
    depends_on:
      - appname-backend

  appname-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - ADMIN_PASSWORD=something
        - DATABASE=appname
        - MONGO_URI=mongodb://appname-mongodb:27017
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app
    depends_on:
      - appname-mongodb

  appname-mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - appname-mongodb:/data/db/appname
    ports:
      - "27017:27017"

volumes:
  appname-mongodb: