version: "3.9"
services:
  appname-frontend:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - /app/build
      - ./client:/app
    networks:
      - appname-network
    depends_on:
      - appname-backend

  appname-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - ADMIN_PASSWORD=something
        - DATABASE=appname
        - MONGO_URI=mongodb://appname-mongodb:27017
        - RABBIT_MQ=amqp://stage:12345@xcodeclazz-mq-backend-stage:5672
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app
    networks:
      - appname-network
      - message-queue-network
    depends_on:
      - appname-mongodb

  appname-mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - appname-mongodb:/data/db/appname
    ports:
      - "27010:27017"
    networks:
      - appname-network

networks:
  appname-network:
    external: true
  message-queue-network:
    external: true

volumes:
  appname-mongodb: