version: "3.9"
services:
  appname-backend-production:
    image: repo/appname-production # PASSWORD REQUIRED
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=ydO4VUkf5eAJ4aub97zhaD8Vm3pPFOC9TTLt528R
      - PORT=8080