version: '3.8'
services:
  bundle:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - MONGO_URI=mongodb://mongodb
        - NODE_ENV=production
        - DATABASE=appname
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080
    volumes:
      - /app/client/node_modules
      - /app/node_modules
      - /app/client/build
      - /app/dist
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - appname:/data/db/appname
    ports:
      - "27017:27017"

volumes:
  appname: