FROM node:alpine

# Please dont change this here, You can change this via outside
ENV ENV=development 

# Set environment variables
ENV MONGO_URI=mongodb://mongodb:27017
ENV KAFKA_ID=appname
ENV DATABASE=appname
ENV KAFKA_1=kafka:9092
ENV JWT_KEY=something
ENV PORT=8080

WORKDIR /app
COPY package*.json .

RUN npm install -g npm@latest
RUN npm install

COPY . .
EXPOSE $PORT
CMD [ "npm", "start" ]