version: '3.8'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - /app/build
      - ./client:/app
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE=appname
        - NODE_ENV=development
        - ADMIN_PASSWORD=something
        - MONGO_URI=mongodb://mongodb
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - appname:/data/db/appname
    ports:
      - "27017:27017"

volumes:
  appname: