version: "3.9"
services:
  appname-backend-stage:
    image: repo/appname-stage # PASSWORD REQUIRED
    restart: always
    ports:
      - "8081:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080