version: '3.9'
services:
  appname-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - ADMIN_PASSWORD=something
        - DATABASE=appname
        - MONGO_URI=mongodb://appname-mongodb:27017
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080
    volumes:
      - /app/client/node_modules
      - /app/node_modules
      - /app/client/build
      - /app/dist
      - .:/app
    depends_on:
      - appname-mongodb

  appname-mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - appname-mongodb:/data/db/appname
    ports:
      - "27017:27017"

volumes:
  appname-mongodb: