name: Refresh Production
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: ⚠️ Production Deploy Trigger
        id: render-production-deployer
        uses: OneHox/render-deploy-api@v1.0.0
        with:
          serviceId: ${{ secrets.WF_RENDER_PRODUCTION_APP_SERVICE_ID }}
          bearer: ${{ secrets.WF_RENDER_PRODUCTION_PROFILE_AUTH_API_TOKEN }}
      - name: 💬 Message
        run: echo "${{ steps.render-production-deployer.outputs.response }}"
